BYOLLM Design
elevenlabs/elevenlabs-docs pull request #485
Opened 2024-11-09 12:24 UTC by hikmet-demir

2024-11-10 09:40 UTC, louisjoecodes requested changes

2024-11-10 09:40 UTC, louisjoecodes commented on developer-guides/BYOLLM.mdx
> +description: "Guide for using your own LLM or server with ElevenLabs SDK."
Missing icon

2024-11-10 09:40 UTC, louisjoecodes commented on developer-guides/BYOLLM.mdx
> +Copy code
Is this Copy code supposed to be here

2024-11-10 09:45 UTC, louisjoecodes requested changes

2024-11-10 09:45 UTC, louisjoecodes commented on developer-guides/BYOLLM.mdx
> +ngrok http --url=elevenlabs.ngrok.app 8013
Would remove elevenlabs here and put 'replace with your own url'

2024-11-10 09:45 UTC, louisjoecodes commented on developer-guides/BYOLLM.mdx
> +Now let's make the changes on the Elevenlabs
'on the elevenlabs' -> 'in ElevenLabs' (or something else)

2024-11-11 14:34 UTC, hikmet-demir commented
making the changes and updating

2024-11-12 16:36 UTC, louisjoecodes approved these changes

2024-11-12 16:37 UTC, merged