[Projects] Quick refresh of docs
elevenlabs/elevenlabs-docs pull request #487
Opened 2024-11-10 20:40 UTC by Mateusz-Kopec

Quick refresh for the new Project editor

2024-11-10 21:02 UTC, louisjoecodes requested changes
🚀 minor changes

2024-11-10 21:02 UTC, louisjoecodes commented on product/projects/overview.mdx
> +**16. Unconverted paragraph** has grey line on the left. Converted paragraphs have darker line next to them.
```suggestion
**16. Unconverted paragraph** have a grey line on the left. Converted paragraphs have darker line next to them.
```

2024-11-10 21:02 UTC, louisjoecodes commented on product/projects/overview.mdx
> +If you want to convert the entire chapter in one go, you can click the convert button in the upper right corner. This will open a page where you can choose to convert either your entire project or in
```suggestion
If you want to convert the entire chapter in one go, you can click the convert button in the upper right corner. This will open a page where you can choose to convert either your entire project or individual chapters. You can also download the entire project or individual chapters. Even after converting the whole chapter, you can still go back and re-generate sections of the book that you are not happy with before downloading the entire thing. However, if you make any changes, you will need to press convert once again for the changes to be reflected in the whole book, so you can download the entire chapter.
```

2024-11-11 10:12 UTC, Mateusz-Kopec commented on product/projects/overview.mdx
> +If you want to convert the entire chapter in one go, you can click the convert button in the upper right corner. This will open a page where you can choose to convert either your entire project or in
duh! 😄

2024-11-11 10:19 UTC, Mateusz-Kopec commented on product/projects/overview.mdx
> +**1. Play** will play currently selected paragraph, if it's not generated yet it will generate it. You can open options to change the button behaviour.
Great idea! 
<img width="762" alt="Screenshot 2024-11-11 at 11 18 54" src="https://github.com/user-attachments/assets/ad28b18c-c4ad-46ce-8f76-993a39ea8ea0">

2024-11-11 10:20 UTC, Mateusz-Kopec commented
@louisjoecodes fixed the issues you found, thanks for the review! Just a note, I think we can do much more here, it's just a quick refresh ahead of release.

2024-11-11 13:59 UTC, louisjoecodes approved these changes

2024-11-11 14:00 UTC, merged