Update projects
elevenlabs/elevenlabs-docs pull request #537
Opened 2024-11-29 17:18 UTC by elevenlabs-laura

- add frames to all images
- add section on auto-regenerate
- add screenshots showing how to enable auto-regenerate

2024-11-29 17:31 UTC, louisjoecodes commented on product/projects/overview.mdx
> +When you have auto-regenerate enabled for your project, we will automatically check the output for any mispronunciations or unwanted audio artefacts.  If we detect any, we will automatically regenera
```suggestion
When the Auto-Regenerate feature is enabled for your project, we will automatically check the output for any mispronunciations or unwanted audio artefacts.  If we detect any, we will automatically regenerate the audio up to twice, at no extra cost.  
```

2024-11-29 17:35 UTC, louisjoecodes reviewed
minor grammar

2024-11-29 17:37 UTC, louisjoecodes approved these changes

2024-11-29 17:37 UTC, louisjoecodes commented on product/projects/overview.mdx
>  Click "Add a new project” and you will be presented with a popup. Here, you can choose to create a new empty project, import an already existing EPUB, PDF, TXT or HTML file, which will then automatic
nit: For step-by-step workflows I would suggest using Mintlfiy [Steps](https://mintlify.com/docs/content/components/steps#steps)

2024-11-29 17:37 UTC, louisjoecodes requested changes
Minor feedback

2024-12-02 16:37 UTC, elevenlabs-laura commented on product/projects/overview.mdx
>  Click "Add a new project” and you will be presented with a popup. Here, you can choose to create a new empty project, import an already existing EPUB, PDF, TXT or HTML file, which will then automatic
I will add Steps to this section on a new branch to keep things clean!

2024-12-02 19:04 UTC, louisjoecodes approved these changes

2024-12-02 19:04 UTC, merged