Update: Changelog
elevenlabs/elevenlabs-docs pull request #547
Opened 2024-12-03 15:34 UTC by Jitendra2603

- Added an image showcasing the new API key features
- Added the updated info on API key features

2024-12-03 15:38 UTC, louisjoecodes requested changes
Thanks! Added comments

2024-12-03 15:38 UTC, louisjoecodes commented on changelog/product-updates.mdx
> +<Frame>![API Keys](/changelog/images/changelog-03-12-24.webp)</Frame>
Image is low quality and doesn't add much so would remove

2024-12-03 15:38 UTC, louisjoecodes commented on changelog/product-updates.mdx
> +- **Workspace API Keys**: Enhanced with access permission controls matching user API key capabilities
This line isn't specific enough - don't understand it

2024-12-03 15:43 UTC, Jitendra2603 commented on changelog/product-updates.mdx
> +<Frame>![API Keys](/changelog/images/changelog-03-12-24.webp)</Frame>
I think none of the images add much, was just following your format, I can add this HQ old one if you want: https://mintlify.s3.us-west-1.amazonaws.com/elevenlabs-docs/api-reference/images/api_key.webp

2024-12-03 15:48 UTC, Jitendra2603 commented on changelog/product-updates.mdx
> +- **Workspace API Keys**: Enhanced with access permission controls matching user API key capabilities
Thoughts on:
- **Credit Usage Limits**: Set specific credit limits for API keys to control costs and manage usage across different use cases by setting "Access"/"No Access" to features like Dubbing, Audio Native, and more. [Check out](https://elevenlabs.io/app/settings/api-keys)
- **Workspace API Keys**: Enhanced with access permission controls matching user API key capabilities like "Read"/"Read and Write" Access to User, Workspace, and History.

2024-12-03 16:23 UTC, louisjoecodes commented on changelog/product-updates.mdx
> +- **Workspace API Keys**: Enhanced with access permission controls matching user API key capabilities
Maybe this is better for WS Api keys: 
Workspace API Keys: Now support access permissions, such as "Read" or "Read and Write," for User, Workspace, and History resources.

2024-12-03 16:23 UTC, louisjoecodes commented on changelog/product-updates.mdx
> +<Frame>![API Keys](/changelog/images/changelog-03-12-24.webp)</Frame>
Then it wouldn't be up to date with the latest functionality right?

2024-12-03 17:42 UTC, Jitendra2603 commented on changelog/product-updates.mdx
> +- **Workspace API Keys**: Enhanced with access permission controls matching user API key capabilities
Added, thanks!

2024-12-05 16:01 UTC, louisjoecodes commented
That's the old api view in the image

2024-12-05 16:13 UTC, merged